spring:
  application:
    name: fin-project

  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  rabbitmq:
    host: rabbit
    port: 5672
    username: guest
    password: guest
    virtual-host: /

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 37229

market:
  alphavantage:
    base-url: https://www.alphavantage.co/query
    api-key: AJYA6A11IA4HBYBI